baseurl = "https://tracybannon.github.io/"
theme = "hugo-geo"
languageCode = "en-us"
title = "Tech with Trac"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "tracybannon@gmail.com"

	profilepic = "img/BlogProfile.JPG"
	
	title = "Tracy Bannon"
	subtitle = "Technical Reflections Blog"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/tracybannon"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/tracybannon"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/tracylbannon/"


	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"